### ISSUE TITLE
About ARToolkit license

### ISSUE THREAD

**Issue by alejogutierrez** [artoolkit/artoolkit5#116]
Hi I wanna know a little bit more about commercial license on ARToolkit.
On the licensing page it says that previously available from ARToolworks, Inc. and no longer available so it's possible to use the project on a commercial purposes like educational mobile apps or something?
Thanks

**Comment by ahundt** [comment]
IANAL, but I suggest reading the [license.txt](https://github.com/artoolkit/artoolkit5/blob/master/LICENSE.txt). It is lgplv3 which means the library can be used for commercial purposes if you are simply using the library. If you modify the library, those modifications must be released.

**Comment by philip-lamb** [comment]
As Andrew correctly noted, the LGPLv3 allows for commercial use, but if you modify ARToolKit itself, you have to share those modifications. Additionally, the examples are mostly under a more permissive simple disclaimer rather than LGPL. If in doubt, look at the license header on each individual file.
