### ISSUE TITLE
Running genTexData unable to read jpeg file

### ISSUE THREAD

**Issue by lya1234** [artoolkit/artoolkit5#130]
i try to run my own marker jpeg file received errors:
unable to open file jpeg for reading
unable to read jpeg image from file 
exiting 

i also run pinball.jpeg.. got similar error

**Comment by BoiseBaked** [comment]
We need more details. You working with ARToolkit5 SDK or GitHub repo? If the repo, are you sync'ed with the latest and greatest master branch? I assume you working on Mac OS X, correct? If so, what version of OS X.

**Comment by BoiseBaked** [comment]
If you're getting the exact error string of "Error: Unable to open file '%s' for reading.\n" it's probably because the command-line parsing of the filename that is passed isn't to robust. I've discovered that using relative paths (pathname beginning with '.' or '..') throws off the open call. For now, just place the jpeg file you want to create a NFT datasets from in the same directory as the genTexData binary and pass it without a path prefix or pass an absolute (full) path to the file.

Of course, this all assumes you're using Mac OS X. Let me know otherwise. Although, that particular code is shared between Windows and Mac OS X.

**Comment by ThorstenBux** [comment]
Closing due to no response in a long time.
Feel free to reopen.

**Comment by sprlee** [comment]
Reading JPEG file...
Error reading JPEG file.
Error: unable to read JPEG image from file './falali.jpg'. Exiting.

centos 6.5

**Comment by sprlee** [comment]
Reading JPEG file...
Error reading JPEG file.
Error: unable to read JPEG image from file './falali.jpg'. Exiting. @ThorstenBux

**Comment by sprlee** [comment]
165     /* Initialize the JPEG decompression object with default error handling. */
    166     memset(&cinfo, 0, sizeof(cinfo));
    167 
    168     /* We set up the normal JPEG error routines, then override error_exit. */
    169     cinfo.err = jpeg_std_error(&jerr.pub);
    170     jerr.pub.error_exit = my_error_exit;
    171     /* Establish the setjmp return context for my_error_exit to use. */
    172     if (setjmp(jerr.setjmp_buffer)) {
    173         /* If we get here, the JPEG code has signaled an error.
    174          * We need to clean up the JPEG object, close the input file, and return.
