### ISSUE TITLE
marker/NFT dataset from on-line location for android

### ISSUE THREAD

**Issue by amet123** [artoolkit/artoolkit5#138]
Is it possible to load 3d content (.osg) and marker/NFT dataset from on-line location for android ? Like if we have 500 NFT images and corresponding 3d models. And we want to load them from online only according to requirement.

**cloud recognition Support Or Some openSource Help**

**Comment by dheeraj192** [comment]
@amet123 I have done this in one of my project. I have kept the markers on amazon s3 and kept the path and id relation in my table. For id I'm using qrcode that is placed on my image. After getting the id on scan I download the markers from server to local device storage after that normal ARToolkit flow works. You can try this for now till there is no cloud recognition support. I am on working on image recognition on server end so that there is no requirement of qrcode.

**Comment by amet123** [comment]
@dheeraj192 thanks buddy , any idea about camera calibration with unity in android artoolkit camera working fine, in unity its not stable proper
