### ISSUE TITLE
iOS ARToolkitWrapper

### ISSUE THREAD

**Issue by RaimundWege** [artoolkit/artoolkit5#173]
Currently I'm working on a cross-platform app with libGDX and want to add an AR feature. The integration of the ARToolkitWrapper for Android was very easy and the feature is already implemented. Now I want the same functionality for the iOS sub-project. I've downloaded the SDK and build the examples but it seems very inconvenient to integrate ARToolkit into an existing iOS app (the only instruction I've found is [here](https://www.evernote.com/shard/s263/sh/4ebc9677-11e3-4441-8579-3bcacfc9c839/1347275e2d93e273)).

Furthermore I'm using the intel multi-os-engine (moe) which is an ahead-of-time compiler and integrated into Android Studio. It is possible to import third party libraries (see [here](https://software.intel.com/en-us/node/633250)) but I can't figure out which of all the libraries I need. I've tried the libARWrapper.a with the headers from 'inlcude/ARWrapper/' but the generated libARWrapper.jar dosen't provide the desired functionality.

Is it possible to build a simple ARToolkitWrapper Xcode project like in Android?

**Comment by yujinfu** [comment]
Hi RaimundWege
how did you integrate libgdx with artoolkit5, I write a demo using libgdx and artoolkit5 on android refer to nftBook demo,
when I lanch my demo , it quickly crash with fatal error (Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1)) , could you please show me a demo about how to integrate libgdx with artoolkit5? thanks very much.

**Comment by BoiseBaked** [comment]
Just like you build and reference ARToolKit for the Android OS and ABIs, you have to build and reference ARToolKit for iOS. The ARToolKit5 SDK for Android and iOS should be cloned from github for the latest support and bug fixes. The ARToolKit SDK provide a set of libraries (and headers) accessed through a platform specific C binary interface. Android uses JNI and iOS uses iOS framework library package - two very different animals. Also, ARToolKit is build using the clang C and C++ compiler, opposed to GNU C++ compiler, which is imposes a restriction to use header files that are only supported by clang or else link time errors result. To build the iOS ARToolkit5 framework using Xcode and the project ARToolKit5iOS.xcodeproj.

YuJinfu, 
nftBook example app currently doesn't build due to the ARToolKit5 build process using the clang C/C++ compiler and its OpenSceneGraph (better known as OSG) dependencies binaries being built with GNU C/C++ compiler. Hence the header related link errors, described above, result. OSG needs to be re-built with clang C/C++ compiler but we don't own the code base and we don't have the time to rebuild the OSG binaries on the behalf of the OSG open source group. For the ARToolKit iOS Xcode project above, this means any target dependencies on ARosg, built by the project, will fail.

**Comment by yujinfu** [comment]
Hi ,@BoiseBaked ,  I build nftBook successfully
I download android-ndk-r11c and setup configuartion in Eclipse , but Eclipse told me that it's not a valid NDK directory (see this link: http://stackoverflow.com/questions/36043047/adt-23-doesnt-like-ndk11)
so I copy the file "ndk-build" from android-ndk-r10e to android-ndk-r11c and Eclipse feel happy ,and everything is ok except multi-nft tracking is still not working.

**Comment by RaimundWege** [comment]
@BoiseBaked did I understand you correctly that I've to build my project on top of ARToolKit5iOS.xcodeproj and there is no way to build just an "ARToolKit.framework" or "ARToolKitWrapper.framework" which I could add to an existing Xcode-Project? I can't find any Framework Build-Configurations in the Xcode-Projects from the Repositories.

**Comment by RaimundWege** [comment]
@yujinfu i've added the aRBaseLib in Android Studio as Module and in the android project I've set a dependency to this module. After that I've implemented the CameraEventListener interface in the AndroidLauncher (which extends from AndroidApplication). I've used the ARActivity implementation as reference for my own implementation.

**Comment by yujinfu** [comment]
@RaimundWege Did you tried posting camera preview data to libgdx Texture? if so , you can handle camera view as an Actor in libgdx, and you do not need to add a surfaceview behind glsurfaceview.

**Comment by RaimundWege** [comment]
@yujinfu That sounds great - thank you!

**Comment by RaimundWege** [comment]
@yujinfu Now I've to ask: how exactly did you accomplish this task? Currently I'm instantiate a CaptureCameraPreview from ARToolKit and add it to the main layout. If I don't add it to the main layout no images get processed.

Do you access the SurfaceTexture in some way, do you push the frame bytes to a pixmap or do you wrote your own CaptureCameraPreviewTexture?

**Comment by yujinfu** [comment]
@RaimundWege I use opencv to get Mat from camera and get rgba byte array from Mat then use opengl es function "glTexImage2D" to post the rgba data to Texture

**Comment by yujinfu** [comment]
@RaimundWege  you can also get yuv data use android's camera api and then convert yuv to rgba in c++ and then use opengl es function "glTexImage2D" to post the rgba data to Texture
