### ISSUE TITLE
ARMovie video appearing small in iOS sample. Can anyone please help?

### ISSUE THREAD

**Issue by dheeraj1921** [artoolkit/artoolkit5#174]

**Comment by BoiseBaked** [comment]
Yes. This is by design. There should be a menu available where you can choose a greater sized viewport. What you have to keep in mind is that these are sample apps that share code (C/C++) amongst many platforms. Maximizing the viewport per device, since UI is always device OS platform and platform SDK specific, would be difficult. Hence, the UI is kept as simple as possible. UI implementation is left to the developer.
