### ISSUE TITLE
Can not run simpleLite on the mac

### ISSUE THREAD

**Issue by zhuyiif** [artoolkit/artoolkit5#176]
Error (2): unable to open camera parameters file "../share/artoolkit-examples/Data/camera_para.dat"

2 bugs.
1. There is no camera_para.dat in /share/artoolkit-examples/Data/ , only in Data2
2. relative path seems not work here.

**Comment by zhuyiif** [comment]
my solution :
int main(int argc, char** argv)
{
    char glutGamemode[32];
#ifdef __APPLE__
    
    char cparam_name[] = "../Resources/Data2/camera_para.dat";
    char vconf[] = "";
    char patt_name[]  = "../Resources/Data/hiro.patt";

#else
    char cparam_name[] = "../share/artoolkit-examples/Data/camera_para.dat";
    char vconf[] = "";
    char patt_name[]  = "../share/artoolkit-examples/Data/hiro.patt";
    
#endif

**Comment by BoiseBaked** [comment]
The file system isn't well organized around supported OS platforms. This will hopefully be fixed in our next SDK release. Really, the Mac OS X camera_para.dat file to be used in the Mac OS X SimpleLite example app should be: [cloned github repo]/examples/ARApp/Data2/camera_para.dat. But it doesn't matter which file you read from, it's a data file that is the same for all OS platforms.

**Comment by zhuyiif** [comment]
@BoiseBaked thanks for comments on that .

**Comment by codeislife99** [comment]
You can also copy paste the .dat file from the Data2 Folder to the Data Folder without changing any internal code.
