### ISSUE TITLE
Error when run simpleLite example

### ISSUE THREAD

**Issue by namkazt** [artoolkit/artoolkit5#183]
i can run simpleLite on bin of ARToolKit v5.3.2r1 Setup (bin-win32-vs120)
but when compile myself from source  it getting that error: 

mainLoop function: 

 at " arglPixelBufferDataUpload(gArglSettings, image->buff); "
image->buff  show "Error reading characters of string."

a point here : PixelFormat check in code when  "arVideoGetPixelFormat" is BGR but camera format is RGB24.
as i see if not error on above than image display is wrong format. (i see like this many time when dev with openCV )
is there any way to set Pixelformat back to RGB24

please let me know if i miss any info.

**Comment by BoiseBaked** [comment]
Hey namkazt, I having a little difficulty understanding what you're trying to ask. Lets start from the beginning.
1) Are you trying to get an ARToolKit5 example app to build and run? Is it SimpleLite example app?
2) What OS platform are you trying target for the example app you wish to build and execute? SimpleLite App is only supported for Mac OS X, iOS, Linux and Windows 10/8.1 (only).
3) Are you encountering a build or runtime error? Or are you asking a question about the source code logic.
4) If you're encountering a runtime error, please describe how you're detecting the error and where (source file and line numbers please) and why you think the code is executing in error.

**Comment by namkazt** [comment]
thankyou @BoiseBaked 
but it's ok now. i don't know but after i restart Visual studio it run as normal. And i have 2 problem like that. after this i get some problem when build simpleNFT but after fixing and research i'm restart and it work like charm. don't know why.

> 1) Are you trying to get an ARToolKit5 example app to build and run? Is it SimpleLite example app?

Yes, i'm trying to compile from source get from github

> 2) What OS platform are you trying target for the example app you wish to build and execute? SimpleLite App is only supported for Mac OS X, iOS, Linux and Windows 10/8.1 (only).

I'm using Windows 10

> 3) Are you encountering a build or runtime error? Or are you asking a question about the source code logic.

It's runtime error, i mean it show up when debug SimpleLite 

> 4) If you're encountering a runtime error, please describe how you're detecting the error and where (source file and line numbers please) and why you think the code is executing in error.

It's just show violent access address as i remember. that cause because pointer "image->buff" point to some where inaccessible

**Comment by BoiseBaked** [comment]
Given this:
> 2) What OS platform are you trying target for the example app you wish to build and execute? SimpleLite App is only supported for Mac OS X, iOS, Linux and Windows 10/8.1 (only).

I'm using Windows 10

What Visual Studio IDE are you using: VS 2013 or VS 2015?
What solution file do you have open and assuming you build for the Windows 10 desktop?

Given this:
> 4) If you're encountering a runtime error, please describe how you're detecting the error and where (source file and line numbers please) and why you think the code is executing in error.

It's just show violent access address as i remember. that cause because pointer "image->buff" point to some where inaccessible.
line 587 : 	glutMainLoop();
line 385 :  arglPixelBufferDataUpload(gArglSettings, image->buff); // crash here.

What the source file names associated with the line numbers above?
Which pointer is bad, "image" or "buff"?
What's the throw exception?

**Comment by namkazt** [comment]
> What Visual Studio IDE are you using: VS 2013 or VS 2015?
What solution file do you have open and assuming you're building for the Windows 10 desktop? Please provide the path from the repo root.

I'm running on VS 2013 ( VS2015 not work yet )
Repo root: you mean this ? "E:\ARtoolkit\Source\artoolkit5\examples\simpleLite"

>What the source file names associated with the line numbers above?
Which pointer is bad, "image" or "buff"?
What's the thrown exception?

examples\simpleLite\simpleLite.c file.
buff is bad pointer and there is no exception just show up "access violation at address [pointer address of buff]"

**Comment by BoiseBaked** [comment]
Good deal! Because I no longer am setup with Visual Studio 2013 and we haven't had time to get Visual Studio 2015 to work with the solution and project files (although, I have no idea why it wouldn't work). Also, I'm sure you're doing this but please use the solution and project files found in the path of: [repo root]/VisualStudio/vs120.

Hey, if have time and are so inclined, can you make a copy of the "[repo root]/VisualStudio/vs120" directory and call the new directory: "[repo root]/VisualStudio/vs140" and try to build and run the solution of example applications projects with Visual Studio 2015. Then perhaps get started on identifying the problem(s) with moving to the Visual Studio 2015 IDE? I'd like to get things working using latest tools for Windows 10.

**Comment by namkazt** [comment]
yes, i'm trying to build with vs140. but have some problems.

for now i'm using ARWrapper implement with bgfx to display.

**Comment by BoiseBaked** [comment]
I don't know what this means: "for now i'm using ARWrapper implement with bgfx to display." Please clarify.

**Comment by namkazt** [comment]
@BoiseBaked  vs140 working prefect.
