### ISSUE TITLE
Problem with libpng when uploading apk to playstore 

### ISSUE THREAD

**Issue by ShinZ6** [artoolkit/artoolkit5#193]
We have made an android app using nftbook project and when we upload the apk there is a vulnerability problem with libpng.

**Comment by ShinZ6** [comment]
How can we fix this ?

**Comment by ShinZ6** [comment]
@ThorstenBux we have to release our app and google doesn't let us publish it because of this, any idea please ?

**Comment by philip-lamb** [comment]
Are you using OpenSceneGraph in your app? If not, you can remove it, as the libpng library is part of OpenSceneGraph.

Otherwise, you could manually recompile OSG yourself if your need is urgent.

**Comment by ShinZ6** [comment]
@philip-lamb we are using the nftBookProj, can we remove it ?

**Comment by BoiseBaked** [comment]
ShinZ6, what Phillip is try to say is that ARToolKit example Android app, nftBookProj, have a dependency on OpenSceneGraph (OSG) libraries. OSG is an external dependency to ARToolKit that ARToolKit has no control over. The dependency on OSG by nftBookProj is what is pulling (linking) in libpng library. Currently, nftBookProj example app project doesn't even build because of the dependency on OSG and the fact that ARToolKit has switched to the clang and clang++ compiler and OSG is still required to be built with the GNU C/C++ compiler. So we wondering how and why you're even using the nftBookProj example project source at all? Bottomline, If you're borrowing the nftBookProject source code for your Android app project, and you don't need the dependency on OSG, and it sounds like you don't, remove the dependency and resubmit your app.

**Comment by ShinZ6** [comment]
@BoiseBaked I fixed my problem by disabling the building of libpng in the Android.mk file since we don't use OSG in our app. You nftBookProject works fine, I managed to build it with android ndk r11c

**Comment by BoiseBaked** [comment]
Oh, so you regressed the NDK you're using. That's why nftBookProject builds for you... AHA! Nice!

**Comment by SanjayAndroidDev** [comment]
@ShinZ6  Can you please provide step or information. How to disabling the building of libpng in the Android.mk file?
