### ISSUE TITLE
Customize camera_para.dat for android

### ISSUE THREAD

**Issue by casio888** [artoolkit/artoolkit5#21]
Hello

im testing my project on different devices, and everytime the camera settings go to 320x280 even when a higher resolution, could be shown (and processed) without effort. 
Is there a way to change this?
I also tried the ARToolkitCamera Calibrator, but it just uploades my "custom file" to a database i cant find...

**Comment by BoiseBaked** [comment]
So you are just concerned that at app startup, a new startup, the
resolution automatically selected is 320X280, that is, the default? What
device and device OS are you targeting with your project?

Thanks
John

**Comment by casio888** [comment]
Yes exactly.
I am targeting Tablets with an Android OS Version 19 or higher.
For my tests I could only use one Tablet and several smartphones.

**Comment by BoiseBaked** [comment]
The thing is you the programmer have to, in Android terms, get the dimension of the inflated surface view control, the surface where the captured video is intended to be previewed, and set the surface texture's buffer size to what the inflated view control can fit. This is done in the ARTK example apps using the now deprecated android.hardware.Camera class in the ARTK Java library source of ARBaseLib (moduleCameraPreferencesActivity.java). Basically, you have to query the device for all the resolutions it supports, pick one that fits in the inflated surface view and then assign the selected resolution as the surface's texture size (through the ARTK SDK API). Warning: implementing the new replacement android.hardware.Camera2 namespace is not trivial. But since you're targeting API level 19, you can probably can stick with the deprecated Camera class (Camera2 package was added in API 21).
