### ISSUE TITLE
Stretched model on android

### ISSUE THREAD

**Issue by PostojePoczekam** [artoolkit/artoolkit5#235]
Hi! I have very strange problem with android build. I think it has something to do with aspect ratio, my camera has 16:9 as, but output image is 4:3.
Do you know how to solve this problem?
http://i.imgur.com/fw9nhRe.png

**Comment by BoiseBaked** [comment]
More details would help here. For example how are you using the ARTK5 SDK, via cloned repo or downloaded code. What platform have you downloaded the SDK to (Mac OS X, Windows 10 or Linux), what mobile platform are you targeting (guessing from the image of your phone, Android?), what app are you building (one of the example ARTK5 Android example apps?) and what type of Android phone are you deploying to. But the short, short answer to your question is when programming to any of the mobile platforms: Android, iOS, Windows 10, each of supports a collection of resolutions and aspect ratios that are made available to the programmer to choose to use for the image viewport. Then it's up to the programmer to not skew the aspect ratio of the image viewport by way of the app's layout design. The ARTK5 Android example apps by no means exhibit sophisticated GUIs. They're basic apps that exhibit basic ARTK5 AR.

**Comment by PostojePoczekam** [comment]
Indeed, the problem was in aspect ratio. However, since the lowest resolution for 16:9 is 720p, overall performance is incredible low, and tracking seem not to work as it's supposed to.

Additional info: Platform Unity 5.5 on Windows 10, source code from unitypackage, target platform Android, target phone Huweii P8

**Comment by BoiseBaked** [comment]
So I assume you're pulling from the artoolkit/arunity5 GitHub repo. Are you also playing with one of the repo's canned Unity examples scenes found under the assets folder here: ARToolKit5-Unity/Example Scenes? If so, which one?

One way to boost performance and not suffer from a slow frame rate due to long game loop iteration intervals, which causes drops of real-time events and adds too much time between the tracking data intervals, is to not use the Unity game loop. That is, don't use Unity at all and instead use the artoolkit/artoolkit5 SDK repo. Create your own simple Android GUI and make sure you put the video capture and tracking logic on a background thread and not the main UI loop. And if your really want to speed things up, use Android native code APIS (the NDK) and implement as little as possible in Android Java.

**Comment by ThorstenBux** [comment]
No reply within 14days -> closing
