### ISSUE TITLE
how to cover marker in armovie sample?

### ISSUE THREAD

**Issue by Mehdi-saber** [artoolkit/artoolkit5#251]
want to cover nft marker in ARmovie android native sample with playing video...
i change video size with changing w&h values in ARMovie.cpp>>nativeDrawFrame fucntion but how can have marker width and height to cover marker?

**Comment by ThorstenBux** [comment]
I don't quite understand what you are aiming for. Would you like to use smaller markers and need to change the settings of the marker size? Or do you need to find out the marker size from the recognition?
You might find help in the forum: http://artoolkit.org/community/forums/

**Comment by Mehdi-saber** [comment]
hi 
thanks for response...
`i want to cover marker(nft) by render video on it in a project based on ARMovie project(android native sample).
i changed code like below in ARMovie.cpp:nativeDrawFrame fucntion but video size changed to zero!

/*float w = 80.0f;
float h = w * (float)movieHeight/(float)movieWidth;*/
float w = markersNFT[i].marker_width;
float h = markersNFT[i].marker_height;`

**Comment by amalcao** [comment]
As the [official documentation](https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_nft_training) describes, the size of  NFT marker `pinball.jpg` is  2048 pixels by 1637 pixels, and the DPI is 220, which means the actual size of the image is 189mm x 236.5mm. I think the size in millimeters is also the size of the marker in its local coordinate system, so set the `w` to `189.0f` and `h` to `236.5f` statically will make the video cover the image perfectly when using `pinball.jpg`.
Since the fields `marker_width` and `marker_height` are not set for NFT markers, you can not get the size info from them. And I haven't found a proper way to get the size info of any NFT markers in the program during runtime.

**Comment by Mehdi-saber** [comment]
thanks for your answer @amalcao 
sounds strange ...
no way to set marker_height&width?!
