### ISSUE TITLE
./build.sh: line 100: /ndk-build: No such file or directory

### ISSUE THREAD

**Issue by yxwandroid** [artoolkit/artoolkit5#263]
Hi, When I try to run the  build.sh I get this error.

Building on Apple Mac OS X (x86_64)
./build.sh: line 100: /ndk-build: No such file or directory
Exiting ndk-build script abnormally terminated.

what   should  I do  !    

I need help  !     

thank !

**Comment by ThorstenBux** [comment]
Hi,

read this and let me know how it goes:
http://artoolkit.org/documentation/doku.php?id=4_Android:android_native

Cheers

**Comment by Wavewash** [comment]
@yxwandroid 
First install the android NDK. To do that open up the Android SDK Manager and find "NDK" under the Build Tools.
![image](https://cloud.githubusercontent.com/assets/315474/24079062/65e2316e-0c55-11e7-9882-2b1b31a7de80.png)
Install the NDK tools. After that is done select and copy the path of where the SDK is located.

Then you'll need to add the path to the build tools in your terminal with the command:
export NDK="/Users/mokakwan/Library/Android/sdk/ndk-bundle"
(Changing the path for what works for you, of course)
**Notice I added the "/ndk-bundle" at the end so that it points to the ndk-build tool, you will need to do this as well!**

And now you should be able to build.
