### ISSUE TITLE
Generating markers

### ISSUE THREAD

**Issue by peterjwest** [artoolkit/artoolkit5#264]
The docs mention different 2D marker dimensions, but I can't find anything more about them, how can I generate these markers? Specifically I would like to use `AR_MATRIX_CODE_4×4_BCH_13_9_3` or any marker encoding with 128 possibilities or more.

**Comment by Neuroforge** [comment]
Hello Peter,

The markers are stored here, but we don't ship the 4x4 markers normally.

https://github.com/artoolkit/artoolkit5/tree/master/doc/patterns

In order to get the markers you'd like to use, please create them from this marker generator.

http://www.artoolworks.com/support/app/marker.php (Server down at time or writing)

Please download the ones i have pregenerated for you here.....

https://www.dropbox.com/s/3e36ukqemfz0ojj/AR_MATRIX_CODE_4x4_BCH_13_9_3.zip?dl=0

Then,

To use the markers in ARToolKit, the following code must be included in ARToolKit setup:
arSetPatternDetectionMode(<#ARHandle handle#>, AR_MATRIX_CODE_DETECTION); 
arSetBorderSize(<#ARHandle handle#>, 0.16667); 
arSetMatrixCodeType(<#ARHandle handle#>, AR_MATRIX_CODE_4x4_BCH_13_9_3);

Kind regards,

Daniel

**Comment by peterjwest** [comment]
Thanks a lot for the detailed response!

Is the code for the marker generator open source?

**Comment by Neuroforge** [comment]
Yes. It is part of ARToolkit5.

Regards,

Daniel

**Comment by garaboncias** [comment]
Please make available again the 4x4 id markers.
I couldn't find anywhere the id marker generator could you give me a hint where is it. 
Or where can i access the specification of the id markers?

**Comment by urfx** [comment]
ditto @garaboncias 

@Neuroforge please could you update the Dropbox link for the 4x4 markers ? Dropbox have made changes to sharing that has broken many links ... including the one you kindly shared above.

**Comment by SimonFrima** [comment]
Hello, would it possible to add marker.php to the github repository so we can run it from our own local server. The specified website server is down. Thank you !

**Comment by philip-lamb** [comment]
I've relocated the generator from the old server to http://au.gmented.com/app/marker/marker.php

**Comment by lyle-univ** [comment]
@Neuroforge, where is the generator? I am unable to find it.

**Comment by ThorstenBux** [comment]
@lyle-univ just follow the link provided by @philip-lamb

**Comment by lyle-univ** [comment]
@ThorstenBux,sorry, I meant the code. What happens when that server goes down?

**Comment by urfx** [comment]
@philip-lamb thanks appreciated and just in time for my project at Audazzle.  

@... I'm expecting that I will need to recompile the code for the unity toolkit in order to use 5x5 markers. Anybody got any experience? 

notes: 4x4 would be fine. 

I'm using the toolkit for in an augmnted card deck and need high hamming to avoid mistaken identity which I've been getting with 3x3 and a deck of 50 unique cards. 

figured 5x5 would be better given the collectable and uniqueness needed for mixing future card decks with the current deck. Aloniverse is on Kickstarter and the Audazzle website. Any help much appreciated . We are making inclusive and accessible games for blind and sighted people to play together.

**Comment by ThorstenBux** [comment]
You can use the 5x5 markers in Unity. It is not available in the Unity inspector UI but it is available on the interface. You should find it in the constants and should be able to set it in a script

**Comment by urfx** [comment]
@ThorstenBux thanks that sounds like just what I'll need. will come back next week with progress.

**Comment by ht44** [comment]
@ThorstenBux @philip-lamb @Neuroforge can you make the server-side code @ http://au.gmented.com/app/marker/marker.php available? Or could you explain which files in ARToolkit5 are responsible for generating markers?

**Comment by atx49559** [comment]
Hi @ThorstenBux @philip-lamb @Neuroforge @ht44 I want the generator server-side code too.
Can you release that? thx

**Comment by nicolocarpignoli** [comment]
@ThorstenBux  @philip-lamb 

This is important. can we have please the code from http://au.gmented.com/app/marker/marker.php?

If the server goes down, I can't find any other generator AT ALL. I think it's crucial to put in open source or at least point to the file on some online repo if already exists.

**Comment by nicolocarpignoli** [comment]
@peterjwest this is not closed, I think it's very important to have the server part of the generator as open source

**Comment by nicolocarpignoli** [comment]
@atx49559  @ht44 and all others

for safety, before something on server side went wrong, I downloaded every barcode markers configuration with Hamming distance > 0 and put them here: https://github.com/nicolocarpignoli/artoolkit-barcode-markers-collection

it contains more than 4800 barcode markers, organized on folders
