### ISSUE TITLE
Artoolkit source code file cannot execute successfully in Android Studio

### ISSUE THREAD

**Issue by tckkenny** [artoolkit/artoolkit5#28]
I downloaded the Artoolkit SDK in https://github.com/artoolkit/artoolkit5 And there is a directory called AndroidStudioProjects, which can be directly opened by using android studio.

I have configured all the jdk, android sdk, ndk.

However, those projects all have the error like this:

E/art: dlopen("/data/app/org.artoolkit.ar.samples.ARMovie-1/lib/arm/libARMovieNative.so", RTLD_LAZY) failed: dlopen failed: could not load library "libcurl.so" needed by "libARMovieNative.so"; caused by library "libcurl.so" not found
The main problem is could not load library "libcurl.so" needed by "libARMovieNative.so".

Can anyone help me please?

**Comment by BoiseBaked** [comment]
Hey tckkenny. I repro'ed the issue you're seeing on Mac OS X deploying to an Android emulator. Obviously, we haven't got the Android Studio NDK thing wired yet. You still have to build the shared library APK dependencies outside of Android Studio first (because we haven't quite figured out how to have it done by Android Studio) but Android Studio is picking up and packing the dependencies. Else, we still have bad static load library load in the Java source. Anyways, I'm working it. Hopefully will have an update soon.

**Comment by BoiseBaked** [comment]
I pushed and merged changes to master that should fix this issue.

**Comment by tckkenny** [comment]
Hi JohnW, thank you for replying me. Finally, I execute successfully by
coping the libcurl.so downloaded from other source and pasting it one by
one to the files.

Best Regards
Kenny

**Comment by BoiseBaked** [comment]
You shouldn't have to that now. If you you do anything like that, please let me know.
