### ISSUE TITLE
2 code question in ARToolkit

### ISSUE THREAD

**Issue by bigeyesung** [artoolkit/artoolkit5#326]
Hi I got 3 questions which I didn't understand clearly.

1 .In Multi-marker reference, arGetTransMatMultiSquare function:
"arUtilMatMul((const ARdouble(*)[4])trans1, (const ARdouble(*)[4])config->marker[max].itrans, trans2)"
        
I know that trans1 is the trans which contains the most pixel, and what does it mean to multiply "config->marker[max].itrans" ?

 2. In arGetMarkerInfo, patternmatch function:
      for( l = 0; l < pattHandle->patt_num; l++ ) { // Consider the whole search space.
            k++;
            while( pattHandle->pattf[k] == 0 ) k++; // No pattern at this slot.
            if( pattHandle->pattf[k] == 2 ) continue; // Pattern at this slot is deactivated.
             for( j = 0; j < 4; j++ ) { // The 4 rotated variants of the pattern.
              sum = 0;
               for(i=0;i<size*size*3;i++) sum += input[i]*pattHandle->patt[k*4 + j][i]; // Correlation operation.
                sum2 = sum / pattHandle->pattpow[k*4 + j] / 
                if( sum2 > max ) { max = sum2; res1 = j; res2 = k; }
            }
        }

Based on http://artoolkit.sourceforge.net/apidoc/structARMarkerInfo.html, I know that "dir" means the marker rotation(direction) so each time we judge rotation based on it.
my question here are:
what is "pattHandle->patt[][]" data structure used for? Could you please tell me more?
sum2 = sum / pattHandle->pattpow[k*4 + j], What does it mean that sum divides Pattern RMS then divides data RMS?

Thanks in advance, cheers.

**Comment by philip-lamb** [comment]
1. marker[max].itrans is the inverse transformation from the individual marker origin to the multimarker set origin. This matrix multiplication transforms each individual marker to the same origin.

2. This is a straight 2D correlation operation. pattHandle->patt[][] contains the 2D template intensities. If an unwarped detected pattern matches a loaded pattern, it will show high correlation. We consider all possible 4 orientations of each pattern in order to determine pattern orientation. This is only one possible way of determining orientation of a fiducial marker (e.g. the barcode markers use a locator pattern in the corners) but it allows us to use almost arbitrary images as templates.
