### ISSUE TITLE
How to set up artoolkit on Android studio

### ISSUE THREAD

**Issue by if412002** [artoolkit/artoolkit5#78]
Hello, can u give me a clear steps to import and compile artoolkit library on Android studio ?
thanks.

**Comment by BoiseBaked** [comment]
First, let me know what dev platform you will be using Android Studio (AS) IDE on - the two supported platforms are Windows 10/8.1 or Mac OS X 9+.

Next, I would recommend the you clone this repo instead of rely on the download SDK (because you are guaranteed to get the latest and greatest).

Next, after you clone a local repo, go get this document: [your local repo root]/AndroidStudioProjects/Docs/AS_Migration.pdf. There is more information then you in this doc but after you download and install the AS IDE, the Android SDK and the Android NDK, follow the instructions related to Gradle, the build system that the AS IDE uses and how to build the Android ARTK dependencies that are used by the AndroidStudioProject example apps. #52

**Comment by alejogutierrez** [comment]
If someone else is looking for an Android studio setup, take a look at this repo
https://github.com/kosiara/artoolkit-android-studio-example
It worked for me using Intellij idea and off course in Android studio on Fedora.
